platform :ios, '9.0'

target 'AirPlayer' do
	
pod 'ReactiveObjC'
pod 'Masonry', '~> 1.1'
pod 'Reachability', '~> 3.1.1'
pod 'MBProgressHUD', '~> 1.1'
pod 'MJRefresh', '~> 3.1'
pod 'FMDB', '~> 2.6.2'
pod 'AFNetworking', '~> 3.1'

end
