source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
target 'DecorationUser' do
    use_frameworks!
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJRefresh', '~> 3.1.15'
pod 'FMDB', '~> 2.7.0'
pod 'SnapKit', '~> 4.0.0'
pod 'HandyJSON', '= 4.0.0-beta.1'
pod 'Alamofire', '~> 4.5.1'
pod 'Kingfisher', '~> 4.2.0'
pod 'CryptoSwift', '= 0.7.1'
pod 'SAMKeychain', '~> 1.5.3'
end
